--criacao das tabelas normalizadas da RFB no oracle
CREATE TABLE RFB_ATIVIDADE_ECONOMICA 
(
  URI VARCHAR(7)
, CNAE VARCHAR(7)
) ;


CREATE TABLE RFB_BAIRRO 
(
  URI VARCHAR(4000 ) 
, ROTULO VARCHAR(50)
) ;

CREATE TABLE RFB_CIDADE 
(
  URI VARCHAR(4000 ) 
, ROTULO VARCHAR(50)
, CODIGO_MUNICIPIO VARCHAR(4)
) 
;

CREATE TABLE RFB_CIDADE_ESTRANGEIRA 
(
  URI VARCHAR(4000 ) 
, ROTULO VARCHAR(55)
) ;

CREATE TABLE RFB_EMPRESA 
(
  URI VARCHAR(4000)
, CNPJ_RAIZ VARCHAR(9)
, RAZAO_SOCIAL VARCHAR(150)
, CAPITAL_SOCIAL INTEGER --ADD COLUNA DA TB ESTABELECIMENTO
, ENTE_FEDERATIVO VARCHAR(156 ) --ADD COLUNA
, URI_OPCAO_SIMPLES VARCHAR(21)
--, E_MEI VARCHAR(5 ) REMOVE COLUNA
, URI_PORTE VARCHAR(13 ) --ADD COLUNA DA TB ESTABELECIMENTO
, URI_MEI VARCHAR(512) --ADD COLUNA PARA NOVA TABELA RFB_OPCAO_MEI
, URI_QUALIFICACAO_REPRESENTANTE VARCHAR(512 ) 
, URI_NATUREZA_LEGAL VARCHAR(512 ) 
, URI_ESTABELECIMENTO_MATRIZ VARCHAR(4000)
) ;

CREATE TABLE RFB_EMPRESA_HOLDING 
(
  URI VARCHAR(4000 ) 
, RAZAO_SOCIAL VARCHAR(150)
, CNPJ_RAIZ VARCHAR(9)
) ;

CREATE TABLE ENDERECO 
(
  URI VARCHAR(2000) 
, NUMERO VARCHAR(6)
, COMPLEMENTO VARCHAR(156)
, CEP VARCHAR(8)
, URI_UNIDADE_FEDERATIVA VARCHAR(19 ) 
, URI_PAIS VARCHAR(4000 ) 
, URI_MUNICIPIO VARCHAR(4000 ) 
, URI_CIDADE_EXTERIOR VARCHAR(4000 ) 
, URI_BAIRRO VARCHAR(4000 ) 
, URI_LOGRADOURO VARCHAR(4000 ) 
) ;

CREATE TABLE RFB_ESTABELECIMENTO 
(
  URI VARCHAR(4000 ) 
, CNPJ VARCHAR(14)
, RAZAO_SOCIAL VARCHAR(150)
, NOME_FANTASIA VARCHAR(56)
--, URI_PORTE VARCHAR(13 ) REMOVE COLUNA PARA TB EMPRESA
, EMAIL VARCHAR(115)
--, CAPITAL_SOCIAL INTEGER REMOVE COLUNA PARA TB EMPRESA
, URI_E_MATRIZ_OU_FILIAL CHAR(6 ) 
, URI_PRINCIPAL_ATIV_ECONOMICA VARCHAR(7)
, DATA_INICIO_ATIV DATE 
, URI_ENDERECO VARCHAR(2000) 
, TELEFONE1 VARCHAR(15)
, TELEFONE2 VARCHAR(15)
, FAX VARCHAR(15)
, URI_SITUACAO VARCHAR(76 ) 
) 
;

CREATE TABLE ESTRANGEIRO 
(
  URI VARCHAR(4000 ) 
, NOME VARCHAR(150)
) 
;

CREATE TABLE LOGRADOURO 
(
  URI VARCHAR(4000 ) 
, ROTULO VARCHAR(60)
, TIPO_LOGRADOURO VARCHAR(21)
) 
;

CREATE TABLE NATUREZA_LEGAL 
(
  URI VARCHAR(512 ) 
, ROTULO VARCHAR(128 ) 
, CODIGO VARCHAR(26 ) 
) 
;

CREATE TABLE OPCAO_SIMPLES 
(
  URI VARCHAR(21)
, TIPO_SIMPLES CHAR(1 ) 
, SUB_CLASSE_SIMPLES VARCHAR(10 ) 
, DATA_EXCLUSAO_SIMPLES DATE 
, DATA_OPCAO_SIMPLES DATE 
) 
;

CREATE TABLE PAIS 
(
  URI VARCHAR(4000 ) 
, ROTULO VARCHAR(280 ) 
, CODIGO_PAIS INTEGER 
) 
;

CREATE TABLE RFB_PESSOA 
(
  URI VARCHAR(4000 ) 
, CPF VARCHAR(14)
, NOME VARCHAR(150)
, FAIXA_ETARIA VARCHAR(1 ) --ADD NOVA COLUNA
) 
;

CREATE TABLE QUALIFICACAO 
(
  URI VARCHAR(512 ) 
, CODIGO_QUALIFICACAO INTEGER 
, ROTULO VARCHAR(128 ) 
) 
;

CREATE TABLE RAZAO_SITUACAO_CADASTRAL 
(
  URI VARCHAR(512 ) 
, ROTULO VARCHAR(128 ) 
, CODIGO_RAZAO_SITUACAO INTEGER
) 
;

CREATE TABLE SITUACAO_CADASTRAL 
(
  URI VARCHAR(76 ) 
, DATA_SITUACAO_CADASTRAL DATE 
, URI_CLASSE_TIPO_SITUACAO VARCHAR(9 ) 
, URI_MOTIVO_SITUACAO VARCHAR(512 ) 
) 
;

CREATE TABLE SITUACAO_ESPECIAL 
(
  URI VARCHAR(47 ) 
, DATA_INICIO_SIT_ESPECIAL DATE 
, DESCRICAO VARCHAR(23)
) 
;

CREATE TABLE SOCIEDADE_COM_ESTRANGEIRO 
(
  URI VARCHAR(4000)
, DATA_INICIO_SOCIEDADE DATE 
, ROTULO VARCHAR(730 ) 
, URI_QUALIFICACAO_REPRESENTANTE VARCHAR(512 ) 
, URI_SOCIO VARCHAR(4000 ) 
, URI_REPRESENTANTE VARCHAR(4000)
, URI_QUALIFICACAO_SOCIO VARCHAR(512 ) 
) 
;

CREATE TABLE SOCIEDADE_COM_HOLDING 
(
  URI VARCHAR(4000)
, ROTULO VARCHAR(730 ) 
, DATA_INICIO_SOCIEDADE DATE 
, URI_QUALIFICACAO_REPRESENTANTE VARCHAR(512 ) 
, URI_SOCIO VARCHAR(4000)
, URI_REPRESENTANTE VARCHAR(4000)
, URI_QUALIFICACAO_SOCIO VARCHAR(512 ) 
) 
;

CREATE TABLE SOCIEDADE_COM_PESSOA_FISICA 
(
  URI VARCHAR(4000)
, DATA_INICIO_SOCIEDADE DATE 
, ROTULO VARCHAR(730 ) 
, URI_SOCIO VARCHAR(4000)
, URI_QUALIFICACAO_SOCIO VARCHAR(512 ) 
) 
;

CREATE TABLE UNIDADE_FEDERATIVA 
(
  URI VARCHAR(19 ) 
, ROTULO VARCHAR(19 ) 
, ABREVIACAO_UF VARCHAR(2)
) 
;

CREATE TABLE TEM_ATIV_ECONOMICA_SECUNDARIA 
(
  URI_ESTABELECIMENTO VARCHAR(4000 ) 
, URI_ATIVIDADE_ECONOMICA VARCHAR(7)
) 
;

CREATE TABLE TEM_ESTABELECIMENTO 
(
  URI_EMPRESA VARCHAR(4000 ) 
, URI_ESTABELECIMENTO VARCHAR(4000 ) 
) 
;

CREATE TABLE TEM_SITUACAO_ESPECIAL 
(
  URI_EMPRESA VARCHAR(4000 ) 
, URI_SITUACAO_ESPECIAL VARCHAR(47 ) 
) 
;

CREATE TABLE TEM_SOCIEDADE_ESTRANGEIRA 
(
  URI_EMPRESA VARCHAR(4000 ) 
, URI_SOCIEDADE VARCHAR(4000 ) 
) 
;

CREATE TABLE TEM_SOCIEDADE_FISICA 
(
  URI_EMPRESA VARCHAR(4000 ) 
, URI_SOCIEDADE VARCHAR(4000 ) 
) 
;

CREATE TABLE TEM_SOCIEDADE_JURIDICA 
(
  URI_EMPRESA VARCHAR(4000 ) 
, URI_SOCIEDADE VARCHAR(4000 ) 
) 
;

CREATE TABLE RFB_OPCAO_MEI 
(
  URI VARCHAR(21)
, OPC_MEI CHAR(1 ) 
, DATA_OPC_MEI DATE 
, DATA_EXC_MEI DATE 
) 
;