--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX16
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_EMPRESA_INDEX16" ON "RFB_EMPRESA" ("ID_ESTABELECIMENTO_MATRIZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_EMPRESA_INDEX3" ON "RFB_EMPRESA" ("RAZAO_SOCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX6
--------------------------------------------------------

  CREATE INDEX "RFB_EMPRESA_INDEX6" ON "RFB_EMPRESA" ("CAPITAL_SOCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX7
--------------------------------------------------------

  CREATE INDEX "RFB_EMPRESA_INDEX7" ON "RFB_EMPRESA" ("TEM_PORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX2
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_EMPRESA_INDEX2" ON "RFB_EMPRESA" ("CNPJ_RAIZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX8
--------------------------------------------------------

  CREATE INDEX "RFB_EMPRESA_INDEX8" ON "RFB_EMPRESA" ("ENTE_FEDERATIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX13
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_EMPRESA_INDEX13" ON "RFB_EMPRESA" ("ID_OPCAO_MEI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX12
--------------------------------------------------------

  CREATE INDEX "RFB_EMPRESA_INDEX12" ON "RFB_EMPRESA" ("ID_OPCAO_SIMPLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX14
--------------------------------------------------------

  CREATE INDEX "RFB_EMPRESA_INDEX14" ON "RFB_EMPRESA" ("ID_QUALIFICACAO_REPRESENTANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_INDEX15
--------------------------------------------------------

  CREATE INDEX "RFB_EMPRESA_INDEX15" ON "RFB_EMPRESA" ("ID_NATUREZA_LEGAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_HOLDING_INDEX1
--------------------------------------------------------

  CREATE INDEX "RFB_EMPRESA_HOLDING_INDEX1" ON "RFB_EMPRESA_HOLDING" ("RAZAO_SOCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_HOLDING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_EMPRESA_HOLDING_PK" ON "RFB_EMPRESA_HOLDING" ("CNPJ_RAIZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_INDEX2" ON "RFB_ENDERECO" ("ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_INDEX3" ON "RFB_ENDERECO" ("CIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_INDEX4" ON "RFB_ENDERECO" ("LOGRADOURO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_INDEX5
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_INDEX5" ON "RFB_ENDERECO" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_INDEX6
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_INDEX6" ON "RFB_ENDERECO" ("COMPLEMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_INDEX7
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_INDEX7" ON "RFB_ENDERECO" ("CEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_INDEX8
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_INDEX8" ON "RFB_ENDERECO" ("BAIRRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_INDEX9
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_INDEX9" ON "RFB_ENDERECO" ("PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_ENDERECO_PK" ON "RFB_ENDERECO" ("ID_ENDERECO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_EXTERIOR_INDEX1
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_EXTERIOR_INDEX1" ON "RFB_ENDERECO_EXTERIOR" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_EXTERIOR_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_EXTERIOR_INDEX2" ON "RFB_ENDERECO_EXTERIOR" ("CEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_EXTERIOR_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_EXTERIOR_INDEX3" ON "RFB_ENDERECO_EXTERIOR" ("PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_EXTERIOR_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_ENDERECO_EXTERIOR_INDEX4" ON "RFB_ENDERECO_EXTERIOR" ("CIDADE_EXTERIOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_ENDERECO_EXTERIOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_ENDERECO_EXTERIOR_PK" ON "RFB_ENDERECO_EXTERIOR" ("ID_ENDERECO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX14
--------------------------------------------------------

  CREATE INDEX "RFB_ESTABELECIMENTO_INDEX14" ON "RFB_ESTABELECIMENTO" ("ID_ATIVIDADE_ECONOMICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_ESTABELECIMENTO_INDEX1" ON "RFB_ESTABELECIMENTO" ("CNPJ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX10
--------------------------------------------------------

  CREATE INDEX "RFB_ESTABELECIMENTO_INDEX10" ON "RFB_ESTABELECIMENTO" ("TELEFONE_2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX11
--------------------------------------------------------

  CREATE INDEX "RFB_ESTABELECIMENTO_INDEX11" ON "RFB_ESTABELECIMENTO" ("FAX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX15
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_ESTABELECIMENTO_INDEX15" ON "RFB_ESTABELECIMENTO" ("ID_ENDERECO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX16
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_ESTABELECIMENTO_INDEX16" ON "RFB_ESTABELECIMENTO" ("ID_SITUACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_ESTABELECIMENTO_INDEX2" ON "RFB_ESTABELECIMENTO" ("RAZAO_SOCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_ESTABELECIMENTO_INDEX3" ON "RFB_ESTABELECIMENTO" ("NOME_FANTASIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_ESTABELECIMENTO_INDEX4" ON "RFB_ESTABELECIMENTO" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX5
--------------------------------------------------------

  CREATE INDEX "RFB_ESTABELECIMENTO_INDEX5" ON "RFB_ESTABELECIMENTO" ("TIPO_ESTABELECIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX7
--------------------------------------------------------

  CREATE INDEX "RFB_ESTABELECIMENTO_INDEX7" ON "RFB_ESTABELECIMENTO" ("DATA_INICIO_ATIV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTABELECIMENTO_INDEX9
--------------------------------------------------------

  CREATE INDEX "RFB_ESTABELECIMENTO_INDEX9" ON "RFB_ESTABELECIMENTO" ("TELEFONE_1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTRANGEIRO_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_ESTRANGEIRO_INDEX2" ON "RFB_ESTRANGEIRO" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTRANGEIRO_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_ESTRANGEIRO_INDEX3" ON "RFB_ESTRANGEIRO" ("ID_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_ESTRANGEIRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_ESTRANGEIRO_PK" ON "RFB_ESTRANGEIRO" ("ID_ESTRANGEIRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_FAIXA_ETARIA_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_FAIXA_ETARIA_INDEX2" ON "RFB_FAIXA_ETARIA" ("DESCRICAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_FAIXA_ETARIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_FAIXA_ETARIA_PK" ON "RFB_FAIXA_ETARIA" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_NATUREZA_LEGAL_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_NATUREZA_LEGAL_INDEX2" ON "RFB_NATUREZA_LEGAL" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_NATUREZA_LEGAL_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_NATUREZA_LEGAL_INDEX3" ON "RFB_NATUREZA_LEGAL" ("ROTULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_NATUREZA_LEGAL_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_NATUREZA_LEGAL_INDEX4" ON "RFB_NATUREZA_LEGAL" ("ID_NATUREZA_LEGAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_OPCAO_MEI_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_OPCAO_MEI_INDEX2" ON "RFB_OPCAO_MEI" ("TIPO_MEI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_OPCAO_MEI_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_OPCAO_MEI_INDEX3" ON "RFB_OPCAO_MEI" ("DATA_EXCLUSAO_SIMPLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_OPCAO_MEI_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_OPCAO_MEI_INDEX4" ON "RFB_OPCAO_MEI" ("DATA_OPCAO_SIMPLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_OPCAO_MEI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_OPCAO_MEI_PK" ON "RFB_OPCAO_MEI" ("ID_OPCAO_MEI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_OPCAO_SIMPLES_INDEX1
--------------------------------------------------------

  CREATE INDEX "RFB_OPCAO_SIMPLES_INDEX1" ON "RFB_OPCAO_SIMPLES" ("TIPO_SIMPLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_OPCAO_SIMPLES_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_OPCAO_SIMPLES_INDEX2" ON "RFB_OPCAO_SIMPLES" ("SUB_CLASSE_SIMPLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_OPCAO_SIMPLES_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_OPCAO_SIMPLES_INDEX3" ON "RFB_OPCAO_SIMPLES" ("DATA_EXCLUSAO_SIMPLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_OPCAO_SIMPLES_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_OPCAO_SIMPLES_INDEX4" ON "RFB_OPCAO_SIMPLES" ("DATA_OPCAO_SIMPLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_OPCAO_SIMPLES_INDEX5
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_OPCAO_SIMPLES_INDEX5" ON "RFB_OPCAO_SIMPLES" ("ID_OPCAO_SIMPLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_PESSOA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_PESSOA_PK" ON "RFB_PESSOA" ("ID_PESSOA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_PESSOA_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_PESSOA_INDEX2" ON "RFB_PESSOA" ("CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_PESSOA_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_PESSOA_INDEX3" ON "RFB_PESSOA" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_PESSOA_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_PESSOA_INDEX4" ON "RFB_PESSOA" ("FAIXA_ETARIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_QUALIFICACAO_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_QUALIFICACAO_INDEX2" ON "RFB_QUALIFICACAO" ("CODIGO_QUALIFICACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_QUALIFICACAO_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_QUALIFICACAO_INDEX3" ON "RFB_QUALIFICACAO" ("ROTULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_QUALIFICACAO_INDEX4
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_QUALIFICACAO_INDEX4" ON "RFB_QUALIFICACAO" ("ID_QUALIFICACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_RAZAO_SITUACAO_CADASTRAL_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_RAZAO_SITUACAO_CADASTRAL_INDEX2" ON "RFB_RAZAO_SITUACAO_CADASTRAL" ("ROTULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_RAZAO_SITUACAO_CADASTRAL_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_RAZAO_SITUACAO_CADASTRAL_INDEX3" ON "RFB_RAZAO_SITUACAO_CADASTRAL" ("CODIGO_RAZAO_SITUACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_RAZAO_SITUACAO_CADASTRAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_RAZAO_SITUACAO_CADASTRAL_PK" ON "RFB_RAZAO_SITUACAO_CADASTRAL" ("ID_RAZAO_SITUACAO_CADASTRAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_REPRESENTANTE_INDEX1
--------------------------------------------------------

  CREATE INDEX "RFB_REPRESENTANTE_INDEX1" ON "RFB_REPRESENTANTE" ("CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_REPRESENTANTE_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_REPRESENTANTE_INDEX2" ON "RFB_REPRESENTANTE" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_REPRESENTANTE_INDEX3
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_REPRESENTANTE_INDEX3" ON "RFB_REPRESENTANTE" ("ID_REPRESENTANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_SITUACAO_CADASTRAL_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_SITUACAO_CADASTRAL_INDEX2" ON "RFB_SITUACAO_CADASTRAL" ("DATA_SITUACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SITUACAO_CADASTRAL_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_SITUACAO_CADASTRAL_INDEX3" ON "RFB_SITUACAO_CADASTRAL" ("SITUACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SITUACAO_CADASTRAL_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_SITUACAO_CADASTRAL_INDEX4" ON "RFB_SITUACAO_CADASTRAL" ("ID_RAZAO_SITUACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SITUACAO_CADASTRAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_SITUACAO_CADASTRAL_PK" ON "RFB_SITUACAO_CADASTRAL" ("ID_SITUACAO_CADASTRAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SITUACAO_ESPECIAL_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_SITUACAO_ESPECIAL_INDEX2" ON "RFB_SITUACAO_ESPECIAL" ("DATA_INICIO_SIT_ESPECIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SITUACAO_ESPECIAL_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_SITUACAO_ESPECIAL_INDEX3" ON "RFB_SITUACAO_ESPECIAL" ("DESCRICAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SITUACAO_ESPECIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_SITUACAO_ESPECIAL_PK" ON "RFB_SITUACAO_ESPECIAL" ("ID_SITUACAO_ESPECIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX10
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX10" ON "RFB_SOCIEDADE_COM_ESTRANGEIRO" ("ID_QUALIFICACAO_SOCIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX11
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX11" ON "RFB_SOCIEDADE_COM_ESTRANGEIRO" ("ID_REPRESENTANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX2" ON "RFB_SOCIEDADE_COM_ESTRANGEIRO" ("DATA_INICIO_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX3" ON "RFB_SOCIEDADE_COM_ESTRANGEIRO" ("ROTULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX8
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX8" ON "RFB_SOCIEDADE_COM_ESTRANGEIRO" ("ID_QUALIFICACAO_REPRESENTANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX9
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_ESTRANGEIRO_INDEX9" ON "RFB_SOCIEDADE_COM_ESTRANGEIRO" ("ID_SOCIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_ESTRANGEIRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_SOCIEDADE_COM_ESTRANGEIRO_PK" ON "RFB_SOCIEDADE_COM_ESTRANGEIRO" ("ID_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_HOLDING_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_HOLDING_INDEX2" ON "RFB_SOCIEDADE_COM_HOLDING" ("ROTULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_HOLDING_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_HOLDING_INDEX3" ON "RFB_SOCIEDADE_COM_HOLDING" ("DATA_INICIO_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_HOLDING_INDEX8
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_HOLDING_INDEX8" ON "RFB_SOCIEDADE_COM_HOLDING" ("ID_QUALIFICACAO_REPRESENTANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_HOLDING_INDEX9
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_HOLDING_INDEX9" ON "RFB_SOCIEDADE_COM_HOLDING" ("ID_QUALIFICACAO_SOCIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_HOLDING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_SOCIEDADE_COM_HOLDING_PK" ON "RFB_SOCIEDADE_COM_HOLDING" ("ID_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_HOLDING_INDEX10
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_HOLDING_INDEX10" ON "RFB_SOCIEDADE_COM_HOLDING" ("ID_SOCIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_HOLDING_INDEX11
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_HOLDING_INDEX11" ON "RFB_SOCIEDADE_COM_HOLDING" ("ID_REPRESENTANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX10
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX10" ON "RFB_SOCIEDADE_COM_PESSOA_FISICA" ("ID_REPRESENTANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX11
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX11" ON "RFB_SOCIEDADE_COM_PESSOA_FISICA" ("ID_SOCIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX2" ON "RFB_SOCIEDADE_COM_PESSOA_FISICA" ("ROTULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX3" ON "RFB_SOCIEDADE_COM_PESSOA_FISICA" ("DATA_INICIO_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX8
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX8" ON "RFB_SOCIEDADE_COM_PESSOA_FISICA" ("ID_QUALIFICACAO_SOCIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX9
--------------------------------------------------------

  CREATE INDEX "RFB_SOCIEDADE_COM_PESSOA_FISICA_INDEX9" ON "RFB_SOCIEDADE_COM_PESSOA_FISICA" ("ID_QUALIFICACAO_REPRESENTANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_SOCIEDADE_COM_PESSOA_FISICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_SOCIEDADE_COM_PESSOA_FISICA_PK" ON "RFB_SOCIEDADE_COM_PESSOA_FISICA" ("ID_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_ATIV_ECONOMICA_SECUNDARIA_INDEX1
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_ATIV_ECONOMICA_SECUNDARIA_INDEX1" ON "RFB_TEM_ATIV_ECONOMICA_SECUNDARIA" ("ID_ESTABELECIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_ATIV_ECONOMICA_SECUNDARIA_INDEX2
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_ATIV_ECONOMICA_SECUNDARIA_INDEX2" ON "RFB_TEM_ATIV_ECONOMICA_SECUNDARIA" ("ID_ATIVIDADE_ECONOMICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_ESTABELECIMENTO_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_TEM_ESTABELECIMENTO_INDEX1" ON "RFB_TEM_ESTABELECIMENTO" ("ID_ESTABELECIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_ESTABELECIMENTO_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_ESTABELECIMENTO_INDEX4" ON "RFB_TEM_ESTABELECIMENTO" ("ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SITUACAO_CADASTRAL_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_TEM_SITUACAO_CADASTRAL_INDEX1" ON "RFB_TEM_SITUACAO_CADASTRAL" ("CNPJ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SITUACAO_CADASTRAL_INDEX2
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_TEM_SITUACAO_CADASTRAL_INDEX2" ON "RFB_TEM_SITUACAO_CADASTRAL" ("ID_SITUACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SITUACAO_CADASTRAL_INDEX3
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_TEM_SITUACAO_CADASTRAL_INDEX3" ON "RFB_TEM_SITUACAO_CADASTRAL" ("CNPJ", "ID_SITUACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SITUACAO_ESPECIAL_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_SITUACAO_ESPECIAL_INDEX3" ON "RFB_TEM_SITUACAO_ESPECIAL" ("ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SITUACAO_ESPECIAL_INDEX4
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_SITUACAO_ESPECIAL_INDEX4" ON "RFB_TEM_SITUACAO_ESPECIAL" ("ID_SITUACAO_ESPECIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SOCIEDADE_ESTRANGEIRA_INDEX4
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_TEM_SOCIEDADE_ESTRANGEIRA_INDEX4" ON "RFB_TEM_SOCIEDADE_ESTRANGEIRA" ("ID_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SOCIEDADE_ESTRANGEIRA_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_SOCIEDADE_ESTRANGEIRA_INDEX3" ON "RFB_TEM_SOCIEDADE_ESTRANGEIRA" ("ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SOCIEDADE_FISICA_INDEX4
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_TEM_SOCIEDADE_FISICA_INDEX4" ON "RFB_TEM_SOCIEDADE_FISICA" ("ID_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SOCIEDADE_FISICA_INDEX3
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_SOCIEDADE_FISICA_INDEX3" ON "RFB_TEM_SOCIEDADE_FISICA" ("ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SOCIEDADE_JURIDICA_INDEX1
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_SOCIEDADE_JURIDICA_INDEX1" ON "RFB_TEM_SOCIEDADE_JURIDICA" ("ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_SOCIEDADE_JURIDICA_INDEX2
--------------------------------------------------------

  CREATE UNIQUE INDEX "RFB_TEM_SOCIEDADE_JURIDICA_INDEX2" ON "RFB_TEM_SOCIEDADE_JURIDICA" ("ID_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RFB_EMPRESA
--------------------------------------------------------

  ALTER TABLE "RFB_EMPRESA" MODIFY ("CNPJ_RAIZ" NOT NULL ENABLE);
  ALTER TABLE "RFB_EMPRESA" ADD CONSTRAINT "RFB_EMPRESA_PK" PRIMARY KEY ("CNPJ_RAIZ")
  USING INDEX (CREATE UNIQUE INDEX "RFB_EMPRESA_INDEX2" ON "RFB_EMPRESA" ("CNPJ_RAIZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_EMPRESA_HOLDING
--------------------------------------------------------

  ALTER TABLE "RFB_EMPRESA_HOLDING" MODIFY ("CNPJ_RAIZ" NOT NULL ENABLE);
  ALTER TABLE "RFB_EMPRESA_HOLDING" ADD CONSTRAINT "RFB_EMPRESA_HOLDING_PK" PRIMARY KEY ("CNPJ_RAIZ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_ENDERECO
--------------------------------------------------------

  ALTER TABLE "RFB_ENDERECO" MODIFY ("ID_ENDERECO" NOT NULL DISABLE);
  ALTER TABLE "RFB_ENDERECO" ADD CONSTRAINT "RFB_ENDERECO_PK" PRIMARY KEY ("ID_ENDERECO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_ENDERECO_EXTERIOR
--------------------------------------------------------

  ALTER TABLE "RFB_ENDERECO_EXTERIOR" MODIFY ("ID_ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "RFB_ENDERECO_EXTERIOR" ADD CONSTRAINT "RFB_ENDERECO_EXTERIOR_PK" PRIMARY KEY ("ID_ENDERECO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_ESTABELECIMENTO
--------------------------------------------------------

  ALTER TABLE "RFB_ESTABELECIMENTO" MODIFY ("CNPJ" NOT NULL ENABLE);
  ALTER TABLE "RFB_ESTABELECIMENTO" ADD CONSTRAINT "RFB_ESTABELECIMENTO_PK" PRIMARY KEY ("CNPJ")
  USING INDEX (CREATE UNIQUE INDEX "RFB_ESTABELECIMENTO_INDEX1" ON "RFB_ESTABELECIMENTO" ("CNPJ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_ESTRANGEIRO
--------------------------------------------------------

  ALTER TABLE "RFB_ESTRANGEIRO" MODIFY ("ID_ESTRANGEIRO" NOT NULL ENABLE);
  ALTER TABLE "RFB_ESTRANGEIRO" ADD CONSTRAINT "RFB_ESTRANGEIRO_PK" PRIMARY KEY ("ID_ESTRANGEIRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_FAIXA_ETARIA
--------------------------------------------------------

  ALTER TABLE "RFB_FAIXA_ETARIA" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "RFB_FAIXA_ETARIA" ADD CONSTRAINT "RFB_FAIXA_ETARIA_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_NATUREZA_LEGAL
--------------------------------------------------------

  ALTER TABLE "RFB_NATUREZA_LEGAL" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "RFB_NATUREZA_LEGAL" ADD CONSTRAINT "RFB_NATUREZA_LEGAL_PK" PRIMARY KEY ("CODIGO")
  USING INDEX (CREATE INDEX "RFB_NATUREZA_LEGAL_INDEX2" ON "RFB_NATUREZA_LEGAL" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_OPCAO_MEI
--------------------------------------------------------

  ALTER TABLE "RFB_OPCAO_MEI" MODIFY ("ID_OPCAO_MEI" NOT NULL ENABLE);
  ALTER TABLE "RFB_OPCAO_MEI" ADD CONSTRAINT "RFB_OPCAO_MEI_PK" PRIMARY KEY ("ID_OPCAO_MEI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_OPCAO_SIMPLES
--------------------------------------------------------

  ALTER TABLE "RFB_OPCAO_SIMPLES" MODIFY ("ID_OPCAO_SIMPLES" NOT NULL ENABLE);
  ALTER TABLE "RFB_OPCAO_SIMPLES" ADD CONSTRAINT "RFB_OPCAO_SIMPLES_PK" PRIMARY KEY ("ID_OPCAO_SIMPLES")
  USING INDEX (CREATE UNIQUE INDEX "RFB_OPCAO_SIMPLES_INDEX5" ON "RFB_OPCAO_SIMPLES" ("ID_OPCAO_SIMPLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" )  ENABLE;
  ALTER TABLE "RFB_OPCAO_SIMPLES" MODIFY ("URI" NOT NULL DISABLE);
--------------------------------------------------------
--  Constraints for Table RFB_PESSOA
--------------------------------------------------------

  ALTER TABLE "RFB_PESSOA" MODIFY ("ID_PESSOA" NOT NULL ENABLE);
  ALTER TABLE "RFB_PESSOA" MODIFY ("CPF" NOT NULL ENABLE);
  ALTER TABLE "RFB_PESSOA" ADD CONSTRAINT "RFB_PESSOA_PK" PRIMARY KEY ("ID_PESSOA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_QUALIFICACAO
--------------------------------------------------------

  ALTER TABLE "RFB_QUALIFICACAO" MODIFY ("ID_QUALIFICACAO" NOT NULL ENABLE);
  ALTER TABLE "RFB_QUALIFICACAO" ADD CONSTRAINT "RFB_QUALIFICACAO_PK" PRIMARY KEY ("ID_QUALIFICACAO")
  USING INDEX (CREATE UNIQUE INDEX "RFB_QUALIFICACAO_INDEX4" ON "RFB_QUALIFICACAO" ("ID_QUALIFICACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_RAZAO_SITUACAO_CADASTRAL
--------------------------------------------------------

  ALTER TABLE "RFB_RAZAO_SITUACAO_CADASTRAL" MODIFY ("ID_RAZAO_SITUACAO_CADASTRAL" NOT NULL ENABLE);
  ALTER TABLE "RFB_RAZAO_SITUACAO_CADASTRAL" ADD CONSTRAINT "RFB_RAZAO_SITUACAO_CADASTRAL_PK" PRIMARY KEY ("ID_RAZAO_SITUACAO_CADASTRAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_SITUACAO_CADASTRAL
--------------------------------------------------------

  ALTER TABLE "RFB_SITUACAO_CADASTRAL" MODIFY ("ID_SITUACAO_CADASTRAL" NOT NULL ENABLE);
  ALTER TABLE "RFB_SITUACAO_CADASTRAL" ADD CONSTRAINT "RFB_SITUACAO_CADASTRAL_PK" PRIMARY KEY ("ID_SITUACAO_CADASTRAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_SITUACAO_ESPECIAL
--------------------------------------------------------

  ALTER TABLE "RFB_SITUACAO_ESPECIAL" MODIFY ("ID_SITUACAO_ESPECIAL" NOT NULL ENABLE);
  ALTER TABLE "RFB_SITUACAO_ESPECIAL" ADD CONSTRAINT "RFB_SITUACAO_ESPECIAL_PK" PRIMARY KEY ("ID_SITUACAO_ESPECIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_SOCIEDADE_COM_ESTRANGEIRO
--------------------------------------------------------

  ALTER TABLE "RFB_SOCIEDADE_COM_ESTRANGEIRO" MODIFY ("ID_SOCIEDADE" NOT NULL ENABLE);
  ALTER TABLE "RFB_SOCIEDADE_COM_ESTRANGEIRO" ADD CONSTRAINT "RFB_SOCIEDADE_COM_ESTRANGEIRO_PK" PRIMARY KEY ("ID_SOCIEDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_SOCIEDADE_COM_HOLDING
--------------------------------------------------------

  ALTER TABLE "RFB_SOCIEDADE_COM_HOLDING" MODIFY ("ID_SOCIEDADE" NOT NULL ENABLE);
  ALTER TABLE "RFB_SOCIEDADE_COM_HOLDING" ADD CONSTRAINT "RFB_SOCIEDADE_COM_HOLDING_PK" PRIMARY KEY ("ID_SOCIEDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_SOCIEDADE_COM_PESSOA_FISICA
--------------------------------------------------------

  ALTER TABLE "RFB_SOCIEDADE_COM_PESSOA_FISICA" MODIFY ("ID_SOCIEDADE" NOT NULL ENABLE);
  ALTER TABLE "RFB_SOCIEDADE_COM_PESSOA_FISICA" ADD CONSTRAINT "RFB_SOCIEDADE_COM_PESSOA_FISICA_PK" PRIMARY KEY ("ID_SOCIEDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_TEM_ESTABELECIMENTO
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_ESTABELECIMENTO" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "RFB_TEM_ESTABELECIMENTO" MODIFY ("ID_ESTABELECIMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_TEM_SITUACAO_CADASTRAL
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SITUACAO_CADASTRAL" MODIFY ("CNPJ" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_TEM_SITUACAO_ESPECIAL
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SITUACAO_ESPECIAL" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "RFB_TEM_SITUACAO_ESPECIAL" ADD CONSTRAINT "RFB_TEM_SITUACAO_ESPECIAL_PK" PRIMARY KEY ("ID_EMPRESA")
  USING INDEX (CREATE INDEX "RFB_TEM_SITUACAO_ESPECIAL_INDEX3" ON "RFB_TEM_SITUACAO_ESPECIAL" ("ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table RFB_TEM_SOCIEDADE_FISICA
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SOCIEDADE_FISICA" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table RFB_ESTABELECIMENTO
--------------------------------------------------------

  ALTER TABLE "RFB_ESTABELECIMENTO" ADD CONSTRAINT "RFB_ESTABELECIMENTO_FK1" FOREIGN KEY ("ID_SITUACAO")
	  REFERENCES "RFB_SITUACAO_CADASTRAL" ("ID_SITUACAO_CADASTRAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RFB_TEM_ESTABELECIMENTO
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_ESTABELECIMENTO" ADD CONSTRAINT "RFB_TEM_ESTABELECIMENTO_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "RFB_EMPRESA" ("CNPJ_RAIZ") ENABLE;
  ALTER TABLE "RFB_TEM_ESTABELECIMENTO" ADD CONSTRAINT "RFB_TEM_ESTABELECIMENTO_FK2" FOREIGN KEY ("ID_ESTABELECIMENTO")
	  REFERENCES "RFB_ESTABELECIMENTO" ("CNPJ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RFB_TEM_SITUACAO_ESPECIAL
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SITUACAO_ESPECIAL" ADD CONSTRAINT "RFB_TEM_SITUACAO_ESPECIAL_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "RFB_EMPRESA" ("CNPJ_RAIZ") ENABLE;
  ALTER TABLE "RFB_TEM_SITUACAO_ESPECIAL" ADD CONSTRAINT "RFB_TEM_SITUACAO_ESPECIAL_FK2" FOREIGN KEY ("ID_SITUACAO_ESPECIAL")
	  REFERENCES "RFB_SITUACAO_ESPECIAL" ("ID_SITUACAO_ESPECIAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RFB_TEM_SOCIEDADE_ESTRANGEIRA
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SOCIEDADE_ESTRANGEIRA" ADD CONSTRAINT "RFB_TEM_SOCIEDADE_ESTRANGEIRA_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "RFB_EMPRESA" ("CNPJ_RAIZ") ENABLE;
  ALTER TABLE "RFB_TEM_SOCIEDADE_ESTRANGEIRA" ADD CONSTRAINT "RFB_TEM_SOCIEDADE_ESTRANGEIRA_FK2" FOREIGN KEY ("ID_SOCIEDADE")
	  REFERENCES "RFB_SOCIEDADE_COM_ESTRANGEIRO" ("ID_SOCIEDADE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RFB_TEM_SOCIEDADE_FISICA
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SOCIEDADE_FISICA" ADD CONSTRAINT "RFB_TEM_SOCIEDADE_FISICA_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "RFB_EMPRESA" ("CNPJ_RAIZ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RFB_TEM_SOCIEDADE_JURIDICA
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SOCIEDADE_JURIDICA" ADD CONSTRAINT "RFB_TEM_SOCIEDADE_JURIDICA_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "RFB_EMPRESA" ("CNPJ_RAIZ") ENABLE;
